jobs:
  attach-pr-number:
    if: github.event_name == 'pull_request'
    name: Attach pull request number
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Create file
      run: 'echo -n ${{ github.event.number }} > pull-request-number

        '
      shell: bash
    - continue-on-error: true
      name: Upload pull request number
      uses: actions/upload-artifact@v2
      with:
        name: pull-request-number-${{ github.event.number }}
        path: pull-request-number
        retention-days: 1
  build:
    name: Build - JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: get-date
      name: Get Date
      run: 'echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"

        '
      shell: bash
    - continue-on-error: true
      id: cache-maven
      name: Cache Maven Repository
      uses: actions/cache@v2
      with:
        key: q2maven-pr-jdk-${{ matrix.java }}-${{ steps.get-date.outputs.date }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Check Wildcards
      run: "if [ $(git grep import -- '*.java' | grep '\\*;' | grep -E -v '(.mvn/|README.md|CONTRIBUTING.md)'\
        \ | wc -l) != 0 ]; then\n  echo \"Please don't use star imports in your Java\
        \ files: \"\n  git grep import | grep '\\*;' | grep -E -v '(.mvn/|README.md|CONTRIBUTING.md)'\n\
        \  exit 1\nfi\n"
    - continue-on-error: true
      name: Install JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: ${{ github.base_ref == 'development' }}
      name: Build Quarkus main
      run: 'git clone https://github.com/quarkusio/quarkus.git

        cd quarkus

        ./mvnw -T1C -e -B --settings .github/mvn-settings.xml clean install -Dquickly-ci

        '
    - continue-on-error: true
      name: Build with Maven
      run: export LANG=en_US && ./mvnw -e -B -fae --settings .github/mvn-settings.xml
        clean install -Dstart-containers
    - continue-on-error: true
      name: Delete Local Artifacts From Cache
      run: rm -rf ~/.m2/repository/org/acme
      shell: bash
    - continue-on-error: true
      if: ${{ failure() || cancelled() }}
      name: Upload build reports (if build failed)
      uses: actions/upload-artifact@v2
      with:
        name: build-reports-Build - JDK ${{ matrix.java }}
        path: '**/target/*-reports/TEST-*.xml

          target/build-report.json

          LICENSE

          '
        retention-days: 2
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
name: Pull Request Build - development
on:
  repository_dispatch:
    types: trigger-ga___build-pr-development.yml
