jobs:
  build-with-native:
    if: github.repository == 'quarkusio/quarkus-quickstarts' || github.event_name
      == 'workflow_dispatch'
    name: ${{matrix.category}}
    needs:
    - generate-json-matrix
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.ref || 'development'
          }}
    - continue-on-error: true
      name: Reclaim Disk Space
      run: .github/ci-prerequisites.sh
    - continue-on-error: true
      id: get-date
      name: Get Date
      run: 'echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"

        '
      shell: bash
    - continue-on-error: true
      id: cache-maven
      name: Cache Maven Repository
      uses: actions/cache@v2
      with:
        key: q2maven-native-${{ steps.get-date.outputs.date }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Install JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build Quarkus main
      run: 'git clone https://github.com/quarkusio/quarkus.git

        cd quarkus

        ./mvnw -T1C -e -B --settings .github/mvn-settings.xml clean install -Dquickly-ci

        '
    - continue-on-error: true
      name: Build Quickstarts with Native
      run: "./mvnw -e -B --settings .github/mvn-settings.xml clean install --fail-at-end\
        \ -Dnative -Dstart-containers \\\n  -Dquarkus.native.container-build=true\
        \ -am -pl \"${{ matrix.test-modules }}\"\n"
    - continue-on-error: true
      name: Delete Local Artifacts From Cache
      run: rm -rf ~/.m2/repository/org/acme
      shell: bash
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-json-matrix.outputs.matrix) }}
      max-parallel: 5
  generate-json-matrix:
    if: github.repository == 'quarkusio/quarkus-quickstarts' || github.event_name
      == 'workflow_dispatch'
    name: Native Tests - Read JSON matrix
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.ref || 'development'
          }}
    - continue-on-error: true
      id: generate
      run: 'json=$(.github/generate-native-matrix.sh | tr -d ''\n'')

        echo "::set-output name=matrix::${json}"

        '
  report:
    if: always() && github.repository == 'quarkusio/quarkus-quickstarts'
    name: Report
    needs:
    - build-with-native
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.ref || 'development'
          }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
        STATUS: ${{ needs.build-with-native.result }}
      name: Report
      run: "echo \"The report step got status: ${STATUS}\"\nsudo apt-get update -o\
        \ Dir::Etc::sourcelist=\"sources.list\" \\\n  -o Dir::Etc::sourceparts=\"\
        -\" -o APT::Get::List-Cleanup=\"0\"\nsudo apt-get install -y gnupg2 gnupg-agent\n\
        echo Installing SDKMAN\ncurl -s \"https://get.sdkman.io\" | bash\nsource ~/.sdkman/bin/sdkman-init.sh\n\
        sed -i -e 's/sdkman_auto_answer=false/sdkman_auto_answer=true/g' ~/.sdkman/etc/config\n\
        sdk install jbang 0.50.1\njbang .github/NativeBuildReport.java token=\"${GITHUB_TOKEN}\"\
        \ status=\"${STATUS}\" issueRepo=\"quarkusio/quarkus\" issueNumber=\"6588\"\
        \ thisRepo=\"${GITHUB_REPOSITORY}\" runId=\"${GITHUB_RUN_ID}\"\n"
name: Native Tests - Development
on:
  repository_dispatch:
    types: trigger-ga___native-build-development.yml
